/*
 * This file is generated by jOOQ.
 */
package dev.yidafu.blog.common.dao.sequences


import dev.yidafu.blog.common.dao.DefaultSchema

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>HIBERNATE_SEQUENCE</code>
 */
val HIBERNATE_SEQUENCE: Sequence<Long> = Internal.createSequence("HIBERNATE_SEQUENCE", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null)
