/*
 * This file is generated by jOOQ.
 */
package dev.yidafu.blog.common.dao

import dev.yidafu.blog.common.dao.tables.BArticle
import dev.yidafu.blog.common.dao.tables.BArticleHistory
import dev.yidafu.blog.common.dao.tables.BConfiguration
import dev.yidafu.blog.common.dao.tables.BSyncTask
import dev.yidafu.blog.common.dao.tables.BUser
import dev.yidafu.blog.common.dao.tables.BUserToken
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultSchema : SchemaImpl("", DefaultCatalog.DEFAULT_CATALOG) {
  companion object {
    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    val DEFAULT_SCHEMA: DefaultSchema = DefaultSchema()
  }

  /**
   * The table <code>B_ARTICLE</code>.
   */
  val B_ARTICLE: BArticle get() = BArticle.B_ARTICLE

  /**
   * The table <code>B_ARTICLE_HISTORY</code>.
   */
  val B_ARTICLE_HISTORY: BArticleHistory get() = BArticleHistory.B_ARTICLE_HISTORY

  /**
   * The table <code>B_CONFIGURATION</code>.
   */
  val B_CONFIGURATION: BConfiguration get() = BConfiguration.B_CONFIGURATION

  /**
   * The table <code>B_SYNC_TASK</code>.
   */
  val B_SYNC_TASK: BSyncTask get() = BSyncTask.B_SYNC_TASK

  /**
   * The table <code>B_USER</code>.
   */
  val B_USER: BUser get() = BUser.B_USER

  /**
   * The table <code>B_USER_TOKEN</code>.
   */
  val B_USER_TOKEN: BUserToken get() = BUserToken.B_USER_TOKEN

  override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

  override fun getTables(): List<Table<*>> =
    listOf(
      BArticle.B_ARTICLE,
      BArticleHistory.B_ARTICLE_HISTORY,
      BConfiguration.B_CONFIGURATION,
      BSyncTask.B_SYNC_TASK,
      BUser.B_USER,
      BUserToken.B_USER_TOKEN,
    )
}
