/*
 * This file is generated by jOOQ.
 */
package dev.yidafu.blog.common.dao.tables.references


import dev.yidafu.blog.common.dao.tables.BArticle
import dev.yidafu.blog.common.dao.tables.BConfiguration
import dev.yidafu.blog.common.dao.tables.BSyncTask
import dev.yidafu.blog.common.dao.tables.BUser
import dev.yidafu.blog.common.dao.tables.BUserToken



/**
 * The table <code>B_ARTICLE</code>.
 */
val B_ARTICLE: BArticle = BArticle.B_ARTICLE

/**
 * The table <code>B_CONFIGURATION</code>.
 */
val B_CONFIGURATION: BConfiguration = BConfiguration.B_CONFIGURATION

/**
 * The table <code>B_SYNC_TASK</code>.
 */
val B_SYNC_TASK: BSyncTask = BSyncTask.B_SYNC_TASK

/**
 * The table <code>B_USER</code>.
 */
val B_USER: BUser = BUser.B_USER

/**
 * The table <code>B_USER_TOKEN</code>.
 */
val B_USER_TOKEN: BUserToken = BUserToken.B_USER_TOKEN
