package dev.yidafu.blog.themes

object PageNames {
  const val ARTICLE_LIST = "ARTICLE_LIST_PAGE"
  const val ARTICLE_DETAIL = "ARTICLE_DETAIL_PAGE"
  const val ABOUT_ME = "ABOUT_ME_PAGE"

  const val ADMIN_LOGIN = "ADMIN_LOGIN"

  const val ADMIN_ARTICLE_LIST = "ADMIN_ARTICLE_LIST_PAGE"
  const val ADMIN_ARTICLE_DETAIL = "ADMIN_ARTICLE_DETAIL_PAGE"
  const val ADMIN_ARTICLE_HISTORY_LIST = "ADMIN_ARTICLE_HISTORY_LIST_PAGE"

  const val ADMIN_CONFIG_PAGE = "ADMIN_CONFIG_PAGE"
  const val ADMIN_CONFIG_APPEARANCE_PAGE = "ADMIN_CONFIG_APPEARANCE_PAGE"
  const val ADMIN_CONFIG_DATA_SOURCE_PAGE = "ADMIN_CONFIG_DATA_SOURCE_PAGE"
  const val ADMIN_CONFIG_SYNC_PAGE = "ADMIN_CONFIG_SYNC_PAGE"

  const val ADMIN_CONFIG_SYNC_LOG_LIST_PAGE = "ADMIN_CONFIG_SYNC_LOG_LIST_PAGE"
  const val ADMIN_CONFIG_SYNC_LOG_DETAIL_PAGE = "ADMIN_CONFIG_SYNC_LOG_DETAIL_PAGE"
  const val ADMIN_CONFIG_SYNC_LOG_OPERATE_PAGE = "ADMIN_CONFIG_SYNC_LOG_OPERATE_PAGE"
}
