package dev.yidafu.blog.themes

object PageNames {
  const val ARTICLE_LIST = "ARTICLE_LIST_PAGE"
  const val ARTICLE_DETAIL = "ARTICLE_DETAIL_PAGE"
  const val ABOUT_ME = "ABOUT_ME_PAGE"

  const val ADMIN_LOGIN = "ADMIN_LOGIN"

  const val ADMIN_DASHBOARD = "ADMIN_DASHBOARD"

  const val ADMIN_ARTICLE_LIST = "ADMIN_ARTICLE_LIST_PAGE"
  const val ADMIN_ARTICLE_DETAIL = "ADMIN_ARTICLE_DETAIL_PAGE"
  const val ADMIN_ARTICLE_HISTORY_LIST = "ADMIN_ARTICLE_HISTORY_LIST_PAGE"

  const val ADMIN_CONFIG_PAGE = "ADMIN_CONFIG_PAGE"
  const val ADMIN_CONFIG_APPEARANCE_PAGE = "ADMIN_CONFIG_APPEARANCE_PAGE"
  const val ADMIN_CONFIG_DATA_SOURCE_PAGE = "ADMIN_CONFIG_DATA_SOURCE_PAGE"
  const val ADMIN_CONFIG_SYNC_PAGE = "ADMIN_CONFIG_SYNC_PAGE"

  const val ADMIN_CONFIG_SYNC_LOG_LIST_PAGE = "ADMIN_CONFIG_SYNC_LOG_LIST_PAGE"
  const val ADMIN_CONFIG_SYNC_LOG_DETAIL_PAGE = "ADMIN_CONFIG_SYNC_LOG_DETAIL_PAGE"
  const val ADMIN_CONFIG_SYNC_LOG_OPERATE_PAGE = "ADMIN_CONFIG_SYNC_LOG_OPERATE_PAGE"

  // 错误页面
  const val ERROR_400 = "ERROR_400_PAGE"
  const val ERROR_401 = "ERROR_401_PAGE"
  const val ERROR_403 = "ERROR_403_PAGE"
  const val ERROR_404 = "ERROR_404_PAGE"
  const val ERROR_405 = "ERROR_405_PAGE"
  const val ERROR_408 = "ERROR_408_PAGE"
  const val ERROR_429 = "ERROR_429_PAGE"
  const val ERROR_500 = "ERROR_500_PAGE"
  const val ERROR_502 = "ERROR_502_PAGE"
  const val ERROR_503 = "ERROR_503_PAGE"
  const val ERROR_504 = "ERROR_504_PAGE"
}
