/*
 * This file is generated by jOOQ.
 */
package dev.yidafu.blog.common.dao.tables

import dev.yidafu.blog.common.dao.DefaultSchema
import dev.yidafu.blog.common.dao.keys.CONSTRAINT_1
import dev.yidafu.blog.common.dao.tables.records.BAccessLogRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime
import kotlin.collections.Collection

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BAccessLog(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, BAccessLogRecord>?,
  parentPath: InverseForeignKey<out Record, BAccessLogRecord>?,
  aliased: Table<BAccessLogRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?,
) : TableImpl<BAccessLogRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
  ) {
  companion object {
    /**
     * The reference instance of <code>B_ACCESS_LOG</code>
     */
    val B_ACCESS_LOG: BAccessLog = BAccessLog()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<BAccessLogRecord> = BAccessLogRecord::class.java

  /**
   * The column <code>B_ACCESS_LOG.ID</code>.
   */
  val ID: TableField<BAccessLogRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

  /**
   * The column <code>B_ACCESS_LOG.ACCESS_TIME</code>.
   */
  val ACCESS_TIME: TableField<BAccessLogRecord, LocalDateTime?> =
    createField(
      DSL.name("ACCESS_TIME"),
      SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
      this,
      "",
    )

  /**
   * The column <code>B_ACCESS_LOG.IP</code>.
   */
  val IP: TableField<BAccessLogRecord, String?> = createField(DSL.name("IP"), SQLDataType.VARCHAR(64), this, "")

  /**
   * The column <code>B_ACCESS_LOG.REFERRER_URL</code>.
   */
  val REFERRER_URL: TableField<BAccessLogRecord, String?> = createField(DSL.name("REFERRER_URL"), SQLDataType.VARCHAR(512), this, "")

  /**
   * The column <code>B_ACCESS_LOG.SOURCE_URL</code>.
   */
  val SOURCE_URL: TableField<BAccessLogRecord, String?> =
    createField(DSL.name("SOURCE_URL"), SQLDataType.VARCHAR(512).nullable(false), this, "")

  /**
   * The column <code>B_ACCESS_LOG.UA</code>.
   */
  val UA: TableField<BAccessLogRecord, String?> = createField(DSL.name("UA"), SQLDataType.VARCHAR(64), this, "")

  /**
   * The column <code>B_ACCESS_LOG.UID</code>.
   */
  val UID: TableField<BAccessLogRecord, String?> = createField(DSL.name("UID"), SQLDataType.VARCHAR(16).nullable(false), this, "")

  private constructor(alias: Name, aliased: Table<BAccessLogRecord>?) : this(alias, null, null, null, aliased, null, null)
  private constructor(
    alias: Name,
    aliased: Table<BAccessLogRecord>?,
    parameters: Array<Field<*>?>?,
  ) : this(alias, null, null, null, aliased, parameters, null)
  private constructor(
    alias: Name,
    aliased: Table<BAccessLogRecord>?,
    where: Condition?,
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>B_ACCESS_LOG</code> table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>B_ACCESS_LOG</code> table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>B_ACCESS_LOG</code> table reference
   */
  constructor() : this(DSL.name("B_ACCESS_LOG"), null)

  override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA

  override fun getIdentity(): Identity<BAccessLogRecord, Long?> = super.getIdentity() as Identity<BAccessLogRecord, Long?>

  override fun getPrimaryKey(): UniqueKey<BAccessLogRecord> = CONSTRAINT_1

  override fun `as`(alias: String): BAccessLog = BAccessLog(DSL.name(alias), this)

  override fun `as`(alias: Name): BAccessLog = BAccessLog(alias, this)

  override fun `as`(alias: Table<*>): BAccessLog = BAccessLog(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): BAccessLog = BAccessLog(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): BAccessLog = BAccessLog(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): BAccessLog = BAccessLog(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): BAccessLog = BAccessLog(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): BAccessLog = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): BAccessLog = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): BAccessLog = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override fun where(condition: SQL): BAccessLog = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override fun where(
    @Stringly.SQL condition: String,
  ): BAccessLog = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override fun where(
    @Stringly.SQL condition: String,
    vararg binds: Any?,
  ): BAccessLog = where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override fun where(
    @Stringly.SQL condition: String,
    vararg parts: QueryPart,
  ): BAccessLog = where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): BAccessLog = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): BAccessLog = where(DSL.notExists(select))
}
