/*
 * This file is generated by jOOQ.
 */
package dev.yidafu.blog.common.dao.tables


import dev.yidafu.blog.common.dao.DefaultSchema
import dev.yidafu.blog.common.dao.keys.CONSTRAINT_CF
import dev.yidafu.blog.common.dao.tables.records.BSyncTaskRecord

import java.time.LocalTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BSyncTask(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BSyncTaskRecord>?,
    parentPath: InverseForeignKey<out Record, BSyncTaskRecord>?,
    aliased: Table<BSyncTaskRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BSyncTaskRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>B_SYNC_TASK</code>
         */
        val B_SYNC_TASK: BSyncTask = BSyncTask()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BSyncTaskRecord> = BSyncTaskRecord::class.java

    /**
     * The column <code>B_SYNC_TASK.ID</code>.
     */
    val ID: TableField<BSyncTaskRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>B_SYNC_TASK.CREATED_AT</code>.
     */
    val CREATED_AT: TableField<BSyncTaskRecord, LocalTime?> = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALTIME, this, "")

    /**
     * The column <code>B_SYNC_TASK.UPDATED_AT</code>.
     */
    val UPDATED_AT: TableField<BSyncTaskRecord, LocalTime?> = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALTIME, this, "")

    /**
     * The column <code>B_SYNC_TASK.CALLBACKURL</code>.
     */
    val CALLBACKURL: TableField<BSyncTaskRecord, String?> = createField(DSL.name("CALLBACKURL"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>B_SYNC_TASK.LOGS</code>.
     */
    val LOGS: TableField<BSyncTaskRecord, String?> = createField(DSL.name("LOGS"), SQLDataType.VARCHAR(1000000000), this, "")

    /**
     * The column <code>B_SYNC_TASK.STATUS</code>.
     */
    val STATUS: TableField<BSyncTaskRecord, Int?> = createField(DSL.name("STATUS"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>B_SYNC_TASK.UUID</code>.
     */
    val UUID: TableField<BSyncTaskRecord, String?> = createField(DSL.name("UUID"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<BSyncTaskRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BSyncTaskRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BSyncTaskRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>B_SYNC_TASK</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>B_SYNC_TASK</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>B_SYNC_TASK</code> table reference
     */
    constructor(): this(DSL.name("B_SYNC_TASK"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<BSyncTaskRecord> = CONSTRAINT_CF
    override fun `as`(alias: String): BSyncTask = BSyncTask(DSL.name(alias), this)
    override fun `as`(alias: Name): BSyncTask = BSyncTask(alias, this)
    override fun `as`(alias: Table<*>): BSyncTask = BSyncTask(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BSyncTask = BSyncTask(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BSyncTask = BSyncTask(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BSyncTask = BSyncTask(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): BSyncTask = BSyncTask(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): BSyncTask = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): BSyncTask = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): BSyncTask = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): BSyncTask = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): BSyncTask = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): BSyncTask = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): BSyncTask = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): BSyncTask = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): BSyncTask = where(DSL.notExists(select))
}
