/*
 * This file is generated by jOOQ.
 */
package dev.yidafu.blog.common.dao.tables

import dev.yidafu.blog.common.dao.DefaultSchema
import dev.yidafu.blog.common.dao.keys.CONSTRAINT_7
import dev.yidafu.blog.common.dao.keys.UK_9X6TW7BOCI1EVWR46R5OMOUKA
import dev.yidafu.blog.common.dao.tables.records.BUserRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BUser(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, BUserRecord>?,
  parentPath: InverseForeignKey<out Record, BUserRecord>?,
  aliased: Table<BUserRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?,
) : TableImpl<BUserRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
  ) {
  companion object {
    /**
     * The reference instance of <code>B_USER</code>
     */
    val B_USER: BUser = BUser()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<BUserRecord> = BUserRecord::class.java

  /**
   * The column <code>B_USER.ID</code>.
   */
  val ID: TableField<BUserRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

  /**
   * The column <code>B_USER.CREATED_AT</code>.
   */
  val CREATED_AT: TableField<BUserRecord, LocalDateTime?> =
    createField(
      DSL.name("CREATED_AT"),
      SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
      this,
      "",
    )

  /**
   * The column <code>B_USER.UPDATED_AT</code>.
   */
  val UPDATED_AT: TableField<BUserRecord, LocalDateTime?> =
    createField(
      DSL.name("UPDATED_AT"),
      SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
      this,
      "",
    )

  /**
   * The column <code>B_USER.EMAIL</code>.
   */
  val EMAIL: TableField<BUserRecord, String?> = createField(DSL.name("EMAIL"), SQLDataType.VARCHAR(255), this, "")

  /**
   * The column <code>B_USER.LOGIN_COUNT</code>.
   */
  val LOGIN_COUNT: TableField<BUserRecord, String?> = createField(DSL.name("LOGIN_COUNT"), SQLDataType.VARCHAR(255), this, "")

  /**
   * The column <code>B_USER.PASSWORD</code>.
   */
  val PASSWORD: TableField<BUserRecord, String?> = createField(DSL.name("PASSWORD"), SQLDataType.VARCHAR(255), this, "")

  /**
   * The column <code>B_USER.STATUS</code>.
   */
  val STATUS: TableField<BUserRecord, Int?> = createField(DSL.name("STATUS"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>B_USER.USERNAME</code>.
   */
  val USERNAME: TableField<BUserRecord, String?> = createField(DSL.name("USERNAME"), SQLDataType.VARCHAR(255), this, "")

  private constructor(alias: Name, aliased: Table<BUserRecord>?) : this(alias, null, null, null, aliased, null, null)
  private constructor(
    alias: Name,
    aliased: Table<BUserRecord>?,
    parameters: Array<Field<*>?>?,
  ) : this(alias, null, null, null, aliased, parameters, null)
  private constructor(alias: Name, aliased: Table<BUserRecord>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>B_USER</code> table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>B_USER</code> table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>B_USER</code> table reference
   */
  constructor() : this(DSL.name("B_USER"), null)

  override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA

  override fun getIdentity(): Identity<BUserRecord, Long?> = super.getIdentity() as Identity<BUserRecord, Long?>

  override fun getPrimaryKey(): UniqueKey<BUserRecord> = CONSTRAINT_7

  override fun getUniqueKeys(): List<UniqueKey<BUserRecord>> = listOf(UK_9X6TW7BOCI1EVWR46R5OMOUKA)

  override fun `as`(alias: String): BUser = BUser(DSL.name(alias), this)

  override fun `as`(alias: Name): BUser = BUser(alias, this)

  override fun `as`(alias: Table<*>): BUser = BUser(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): BUser = BUser(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): BUser = BUser(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): BUser = BUser(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): BUser = BUser(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): BUser = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): BUser = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): BUser = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override fun where(condition: SQL): BUser = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override fun where(
    @Stringly.SQL condition: String,
  ): BUser = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override fun where(
    @Stringly.SQL condition: String,
    vararg binds: Any?,
  ): BUser = where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override fun where(
    @Stringly.SQL condition: String,
    vararg parts: QueryPart,
  ): BUser = where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): BUser = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): BUser = where(DSL.notExists(select))
}
