/*
 * This file is generated by jOOQ.
 */
package dev.yidafu.blog.common.dao.tables.records


import dev.yidafu.blog.common.dao.tables.BSyncTask

import java.time.LocalTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BSyncTaskRecord() : UpdatableRecordImpl<BSyncTaskRecord>(BSyncTask.B_SYNC_TASK) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var createdAt: LocalTime?
        set(value): Unit = set(1, value)
        get(): LocalTime? = get(1) as LocalTime?

    open var updatedAt: LocalTime?
        set(value): Unit = set(2, value)
        get(): LocalTime? = get(2) as LocalTime?

    open var callbackurl: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var logs: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var status: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var uuid: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised BSyncTaskRecord
     */
    constructor(id: Long? = null, createdAt: LocalTime? = null, updatedAt: LocalTime? = null, callbackurl: String? = null, logs: String? = null, status: Int? = null, uuid: String? = null): this() {
        this.id = id
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.callbackurl = callbackurl
        this.logs = logs
        this.status = status
        this.uuid = uuid
        resetChangedOnNotNull()
    }
}
